-- ==========================================================================
-- SwiftShare - Premium SaaS Chat Application Database Schema
-- File: schema.sql
-- Description: Cloudflare D1 (SQLite) initialization script.
-- Creates necessary tables for Users, Messages, and Call History.
-- ==========================================================================

-- Enable foreign keys to maintain relational integrity
PRAGMA foreign_keys = ON;

-- --------------------------------------------------------------------------
-- 1. USERS TABLE
-- Stores user authentication data and profile information.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Users (
    id TEXT PRIMARY KEY,                           -- Unique user ID generated by backend (e.g., UUID)
    username TEXT NOT NULL UNIQUE,                 -- Unique handle (e.g., shohag_pro)
    mobile TEXT NOT NULL UNIQUE,                   -- Registered mobile number
    password_hash TEXT NOT NULL,                   -- Securely hashed password (bcrypt)
    name TEXT NOT NULL,                            -- Display name
    profile_pic TEXT DEFAULT 'default_avatar.jpg', -- URL or path to image in Cloudflare R2
    status TEXT DEFAULT 'offline',                 -- Current user status (online/offline)
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- Account creation time
    last_seen DATETIME DEFAULT CURRENT_TIMESTAMP   -- Last activity timestamp
);

-- Index for faster lookups during login
CREATE INDEX IF NOT EXISTS idx_users_username ON Users(username);
CREATE INDEX IF NOT EXISTS idx_users_mobile ON Users(mobile);


-- --------------------------------------------------------------------------
-- 2. MESSAGES TABLE
-- Stores all one-to-one chat messages securely.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Messages (
    id TEXT PRIMARY KEY,                           -- Unique message ID (UUID)
    sender_id TEXT NOT NULL,                       -- ID of the user sending the message
    receiver_id TEXT NOT NULL,                     -- ID of the user receiving the message
    message_type TEXT DEFAULT 'text',              -- Type: 'text', 'image', 'file'
    content TEXT NOT NULL,                         -- The actual text or the URL to the file in R2
    file_name TEXT,                                -- Original name of the file (if type is file/image)
    file_size TEXT,                                -- Size of the file in MB/KB (if applicable)
    is_read BOOLEAN DEFAULT 0,                     -- 0 for unread, 1 for read
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- Time the message was sent
    
    -- Foreign Key Constraints
    FOREIGN KEY (sender_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES Users(id) ON DELETE CASCADE
);

-- Index to quickly load chat history between two specific users
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON Messages(sender_id, receiver_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON Messages(created_at);


-- --------------------------------------------------------------------------
-- 3. CALL_HISTORY TABLE
-- Logs audio and video call attempts, duration, and status.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Call_History (
    id TEXT PRIMARY KEY,                           -- Unique call ID (UUID)
    caller_id TEXT NOT NULL,                       -- User who initiated the call
    receiver_id TEXT NOT NULL,                     -- User who received the call
    call_type TEXT NOT NULL,                       -- 'audio' or 'video'
    status TEXT NOT NULL,                          -- 'missed', 'completed', 'rejected'
    started_at DATETIME DEFAULT CURRENT_TIMESTAMP, -- When the call rang
    ended_at DATETIME,                             -- When the call finished
    duration_seconds INTEGER DEFAULT 0,            -- Length of the call
    
    -- Foreign Key Constraints
    FOREIGN KEY (caller_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES Users(id) ON DELETE CASCADE
);

-- Index for retrieving a user's recent call logs
CREATE INDEX IF NOT EXISTS idx_calls_participants ON Call_History(caller_id, receiver_id);


-- ==========================================================================
-- Example Initial Data Injection (For Testing Purposes Only)
-- Replace the hashed password with a real hash in production.
-- ==========================================================================
/*
INSERT INTO Users (id, username, mobile, password_hash, name, profile_pic) 
VALUES (
    'user_101', 
    'shohag', 
    '+8801700000000', 
    '$2b$10$YourHashedPasswordHere...', 
    'Md Shohag Islam', 
    'shohag.jpg'
);
*/